# Generated by Django 3.2.9 on 2021-12-14 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('kigali', 'kigali'), ('south', 'south'), ('east', 'east'), ('west', 'west')], default='kigali', max_length=200)),
                ('property_type', models.CharField(choices=[('house', 'house'), ('car', 'car'), ('land', 'land'), ('other', 'other')], max_length=200)),
                ('amount_per_month', models.IntegerField(default=10000)),
                ('detail', models.CharField(default='', max_length=250)),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('available', models.BooleanField(default=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Property_registration',
                'ordering': ['id'],
            },
        ),
    ]
