# Generated by Django 3.2.9 on 2021-12-15 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_property_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_view', models.CharField(choices=[('initial', 'initial'), ('request', 'request'), ('approved', 'approved'), ('denied', 'denied'), ('canceled', 'canceled')], max_length=50)),
                ('property_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_req', to='users.property_registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Request',
            },
        ),
    ]
