# Generated by Django 3.2.9 on 2021-12-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Request_Property',
        ),
    ]
