# Generated by Django 3.2.9 on 2021-12-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_request_request_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request_property',
            options={'verbose_name_plural': 'Request_Property'},
        ),
        migrations.AlterField(
            model_name='request_property',
            name='status_view',
            field=models.CharField(choices=[('initial', 'initial'), ('request', 'request'), ('approved', 'approved'), ('denied', 'denied'), ('canceled', 'canceled')], default='initial', max_length=50),
        ),
    ]
