# Generated by Django 3.2.9 on 2021-12-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211222_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_property',
            old_name='user',
            new_name='user_request',
        ),
        migrations.AddField(
            model_name='request_property',
            name='owner_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_name_property', to='users.user'),
            preserve_default=False,
        ),
    ]
