# Generated by Django 3.2.9 on 2021-12-24 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211223_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_property',
            name='time_done',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 12, 21, 3, 941664, tzinfo=utc)),
        ),
    ]
