# Generated by Django 3.2.9 on 2022-01-05 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_request_property_time_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property_registration',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Property_registration'},
        ),
        migrations.AlterModelOptions(
            name='request_property',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Request_Property'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='profile.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='request_property',
            name='time_done',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 18, 33, 31, 332948, tzinfo=utc)),
        ),
    ]
