# Generated by Django 3.2.9 on 2022-01-10 13:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220109_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_property',
            name='time_done',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 13, 57, 28, 329151, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Payment_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('payment_reference', models.CharField(max_length=250)),
                ('time_done', models.DateTimeField(default=datetime.datetime(2022, 1, 10, 13, 57, 28, 329151, tzinfo=utc))),
                ('payment_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='users.request_property')),
                ('user_paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payment_Report',
                'ordering': ['-id'],
            },
        ),
    ]
