# Generated by Django 3.2.9 on 2022-01-19 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220110_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('subject', models.CharField(max_length=200)),
                ('ClientMessage', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='payment_report',
            name='time_done',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 14, 43, 34, 634568, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request_property',
            name='time_done',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 14, 43, 34, 634568, tzinfo=utc)),
        ),
    ]
