# Generated by Django 3.2.9 on 2022-01-19 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220119_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmessage',
            old_name='ClientMessage',
            new_name='clientMessage',
        ),
        migrations.AlterField(
            model_name='payment_report',
            name='time_done',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 15, 8, 48, 946199, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request_property',
            name='time_done',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 15, 8, 48, 946199, tzinfo=utc)),
        ),
    ]
