# Generated by Django 3.2.9 on 2021-12-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_registration_owner_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property_registration',
        ),
    ]
